
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

##### ELYSIUM #####
# 3rd-party modules
#load_module /etc/nginx/modules/ngx_http_image_filter_module.so;
#load_module /etc/nginx/modules/ngx_http_xslt_filter_module.so;
#load_module /etc/nginx/modules/ngx_http_echo_module.so;
load_module /etc/nginx/modules/ngx_http_headers_more_filter_module.so;
load_module /etc/nginx/modules/ngx_http_geoip2_module.so;
load_module /etc/nginx/modules/ngx_stream_geoip2_module.so;
load_module /etc/nginx/modules/ngx_http_modsecurity_module.so;
load_module /etc/nginx/modules/ngx_http_vhost_traffic_status_module.so;
###################

events {
    worker_connections  4096;
}


http {

    ##### ELYSIUM #####
    proxy_ssl_server_name on;
    proxy_ssl_verify off;
    ###################

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # don't send the nginx version number in error pages and Server header
    server_tokens off;

    ### IF GEOIP ENABLED
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for" '
    #                  '$ssl_protocol $ssl_cipher '
    #                  '"$geoip2_data_country_code" "$geoip2_data_city_name"';

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '$ssl_protocol $ssl_cipher ';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    ##### ELYSIUM #####
    variables_hash_max_size 1024;
    variables_hash_bucket_size 128;
    ###################

    include /etc/nginx/conf.d/*.conf;

    ##### ELYSIUM #####
    # map directives
    map "$request_method $uri" $loggable {
        default   0;
        include /etc/nginx/apm.d/*.map;
    }

    ### IF GEOIP ENABLED
    #geoip2 /etc/nginx/geoip/GeoLite2-Country.mmdb {
    #    auto_reload 1d;
    #    $geoip2_metadata_country_build metadata build_epoch;
    #    $geoip2_data_country_code source=$http_x_forwarded_for country iso_code;
    #    $geoip2_data_country_name source=$http_x_forwarded_for country names en;
    #}

    #geoip2 /etc/nginx/geoip/GeoLite2-City.mmdb {
    #    auto_reload 1d;
    #    $geoip2_metadata_city_build metadata build_epoch;
    #    $geoip2_data_city_name source=$http_x_forwarded_for city names en;
    #}

    # ALLOWED COUNTRIES
    #map $geoip2_data_country_code $allowed_country {
    #    default yes;
    #    include /etc/nginx/geoip/*.conf;
    #}

    vhost_traffic_status_zone;
    vhost_traffic_status_dump /var/log/nginx/vhost/vts.db;
    ##########################
}
